#!/usr/bin/env python3
"""機能紹介: 型ごとの値の入れ方と保存(CE-1〜CE-31・WB-9 など)。"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import tour  # noqa: E402

TITLE = "型ごとに値を入れて保存する"


def steps(t):
    t.keys("C-l")
    t.say("列の型(リスト・日付・数・チェック・タグ)ごとに、合った入れ方が出る")
    t.run("mdgrid .")
    t.say("status の列で Enter。同じ列でほかのノートが使っている値から選べる")
    t.keys("Enter")
    t.pause(1.5)
    t.keys("Down")
    t.say("doing を選んで Enter(打てば新しい値も入れられる)")
    t.keys("Enter")
    t.say("直したセルには * が付く。保存するまでファイルには書かない")
    t.say("右の due は日付の列。Enter でカレンダーが開く")
    t.keys("l", "Enter")
    t.say("矢印で日を動かす(↓ で1週間後、→ で次の日)")
    t.keys("Down", "Right")
    t.pause(1)
    t.keys("Enter")
    t.say("priority は数の列。数として読めない値は入れない")
    t.keys("l", "Enter")
    t.pause(0.8)
    t.back(3)
    t.type("5")
    t.pause(0.8)
    t.keys("Enter")
    t.say("done はチェックの列。Enter で true と false が切り替わる")
    t.keys("l", "Enter")
    t.pause(1)
    t.say("tags はリストの列。Enter で、付ける値を選ぶ窓が出る")
    t.keys("l", "Enter")
    t.pause(1.5)
    t.say("Space で付け外し。「家」を足して Enter")
    t.keys("Space")
    t.pause(0.8)
    t.keys("Enter")
    t.say("Ctrl+S で保存。書く前に、ファイルごとの差分を見せる")
    t.keys("C-s")
    t.pause(1)
    t.say("直したキーの行だけが変わる。ほかの行・順・コメント・本文には触らない", 4)
    t.say("Enter で書く")
    t.keys("Enter")
    t.pause(1)
    t.say("保存した。ファイルの中身を見てみる")
    t.type("q")
    t.pause(1)
    t.keys("C-l")
    t.run("head -9 タスク/会議の議事録を書く.md")
    t.say("日時の列では、カレンダーに時刻の欄も出る", 3)
    t.keys("C-l")
    t.run("cd ../schedule && mdgrid .")
    t.keys("l", "Enter")
    t.pause(1)
    t.say("Ctrl+O で時刻の欄へ。↑↓ で15分ずつ")
    t.keys("C-o")
    t.pause(0.6)
    t.keys("Up", "Up")
    t.pause(1)
    t.keys("Enter")
    t.say("14:30 が 15:00 になった。保存しないで終わると、確かめが出る", 4)
    t.type("q")
    t.pause(1.5)
    t.say("d で捨てて終わる")
    t.type("d")
    t.pause(1)


if __name__ == "__main__":
    tour.main(TITLE, steps)
